### ISSUE TITLE
Not coming online on Discord

### ISSUE THREAD

**Issue by Evancleaveland** [stephanlensky/hyacinth#39]
I have configured everything as described in the guide and I am running the bot on vm Ubuntu but no matter what I troubleshot, it will not come online in discord.

Using docker-compose build I get no errors and it runs through all steps

then I use docker-compose up service and again no errors, I get hyacinth_service_1 exited with code 0 

but the bot is not coming online on discord. I have triple checked all configurations, the .env file and insured I have all required pre requisites.

after hours of troubleshooting, I’m hoping for any guidance 

thank you 🙏🙏

**Comment by stephanlensky** [comment]
Hi, can you please attach the output from the container before it exits?

**Comment by Evancleaveland** [comment]
Thank you for the reply, see attached log
<img width="1280" alt="Screen Shot 2023-08-12 at 9 47 19 AM" src="https://github.com/stephanlensky/hyacinth/assets/141958497/d27ad203-e396-405f-b53d-1b54197fc504">

**Comment by stephanlensky** [comment]
Do you have a file named `run` in the hyacinth directory? I think that would cause the behavior you're seeing.

I just pushed a change that fixes this bug. Can you either

1. Remove the `run` file, or
2. Download the latest version

and then try again?

**Comment by Evancleaveland** [comment]
Thank you so much for the response! I do not see a file named run nor have I added one, but I downloaded the latest version and rebuilt the image and received more errors that i had not received before, could you please take a look at the log? I would appreciate it so much!!!
[outputfile.txt](https://github.com/stephanlensky/hyacinth/files/12328415/outputfile.txt)

**Comment by Evancleaveland** [comment]
Okay please disregard previous message, I was able to complete the build successfully by clearing space on my drive and running this Note: This error originates from the build backend, and is likely not a problem with poetry but with untokenize (0.1.1) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "untokenize (==0.1.1)"'.

I am now getting a different error running Docker-compose up service. Please see below

evan@evan-VirtualBox:~/hyacinth$ docker-compose up service
hyacinth_browserless_1 is up-to-date
hyacinth_db_1 is up-to-date
Starting hyacinth_service_1 ... done
Attaching to hyacinth_service_1
service_1      | Traceback (most recent call last):
service_1      |   File "<string>", line 1, in <module>
service_1      |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
service_1      |     return _bootstrap._gcd_import(name[level:], package, level)
service_1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service_1      |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
service_1      |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
service_1      |   File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
service_1      |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
service_1      |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
service_1      |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
service_1      |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
service_1      |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
service_1      |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
service_1      |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
service_1      |   File "/app/hyacinth/__init__.py", line 24, in <module>
service_1      |     _configure_logging()
service_1      |   File "/app/hyacinth/__init__.py", line 9, in _configure_logging
service_1      |     settings = get_settings()
service_1      |                ^^^^^^^^^^^^^^
service_1      |   File "/app/hyacinth/settings.py", line 66, in get_settings
service_1      |     return Settings()  # type: ignore
service_1      |            ^^^^^^^^^^
service_1      |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.11/lib/python3.11/site-packages/pydantic_settings/main.py", line 71, in __init__
service_1      |     super().__init__(
service_1      |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.11/lib/python3.11/site-packages/pydantic/main.py", line 159, in __init__
service_1      |     __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
service_1      | pydantic_core._pydantic_core.ValidationError: 6 validation errors for Settings
service_1      | google_geocoding_api_key
service_1      |   Field required [type=missing, input_value={'tz': 'America/New_York'...6xqEDre0DokM2vRte4Kb8E'}, input_type=dict]
service_1      |     For further information visit https://errors.pydantic.dev/2.1/v/missing
service_1      | s3_url
service_1      |   Field required [type=missing, input_value={'tz': 'America/New_York'...6xqEDre0DokM2vRte4Kb8E'}, input_type=dict]
service_1      |     For further information visit https://errors.pydantic.dev/2.1/v/missing
service_1      | s3_access_key
service_1      |   Field required [type=missing, input_value={'tz': 'America/New_York'...6xqEDre0DokM2vRte4Kb8E'}, input_type=dict]
service_1      |     For further information visit https://errors.pydantic.dev/2.1/v/missing
service_1      | s3_secret_key
service_1      |   Field required [type=missing, input_value={'tz': 'America/New_York'...6xqEDre0DokM2vRte4Kb8E'}, input_type=dict]
service_1      |     For further information visit https://errors.pydantic.dev/2.1/v/missing
service_1      | s3_bucket
service_1      |   Field required [type=missing, input_value={'tz': 'America/New_York'...6xqEDre0DokM2vRte4Kb8E'}, input_type=dict]
service_1      |     For further information visit https://errors.pydantic.dev/2.1/v/missing
service_1      | browserless_url
service_1      |   Field required [type=missing, input_value={'tz': 'America/New_York'...6xqEDre0DokM2vRte4Kb8E'}, input_type=dict]
service_1      |     For further information visit https://errors.pydantic.dev/2.1/v/missing
service_1      | make: *** [Makefile:30: run] Error 1
hyacinth_service_1 exited with code 2

**Comment by stephanlensky** [comment]
Looks like some optional settings were accidentally not actually marked as optional 🤦. Sorry about that.

I just pushed a fix, could you try pulling the latest version and starting the service again? You should not need to rebuild the image.

**Comment by Evancleaveland** [comment]
No problem at all!!

You are a LIFE SAVER thank you so much, I am now up and running. I cannot wait to test this out!!

I appreciate you taking time to give me a hand!!! Thank you so much for all of your help and thank you for building such an awesome application!!!
