### ISSUE TITLE
Geotagging error 

### ISSUE THREAD

**Issue by mattwyd** [stephanlensky/hyacinth#42]
Traceback (most recent call last):
  File "/app/hyacinth/monitor.py", line 95, in __safe_poll_search
    listings = await search_spec.plugin.get_listings(search_spec.search_params, after_time)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plugins/marketplace/plugin.py", line 38, in get_listings
    return await get_listings(search_params, after_time, limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plugins/marketplace/client.py", line 27, in get_listings
    async for listing in search:
  File "/app/plugins/marketplace/client.py", line 78, in _search
    await _enrich_listing(listing)
  File "/app/plugins/marketplace/client.py", line 94, in _enrich_listing
    location = reverse_geotag((listing.latitude, listing.longitude))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/hyacinth/util/geo.py", line 41, in reverse_geotag
    return _reverse_geotag_local(geotag)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/hyacinth/util/geo.py", line 151, in _reverse_geotag_local
    geolocator = get_local_geolocator()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/hyacinth/util/geo.py", line 147, in get_local_geolocator
    return LocalReverseGeocoder()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/hyacinth/util/geo.py", line 82, in __init__
    self.ensure_geospatial_datasets_downloaded()
  File "/app/hyacinth/util/geo.py", line 114, in ensure_geospatial_datasets_downloaded
    raise FileNotFoundError(
FileNotFoundError: Could not find local geospatial data. Please download gadm36_USA.gpkg and cities1000.txt to use local geocoding.

**Comment by stephanlensky** [comment]
Hi there, thanks for checking out this project. You'll need a few files in order to use the local geocoder, I've uploaded them to drive [here](https://drive.google.com/drive/folders/1pkvMajBYcE1Gy3Do1eSF_C5nsmJERDSS?usp=drive_link) for you.

Alternatively, you can set a Google geocoder API key and toggle local geocoding **off** [here](https://github.com/stephanlensky/hyacinth/blob/main/hyacinth/settings.py#L35-L40).

**Comment by mattwyd** [comment]
thanks for making it! i checked out some of your work its really cool. i just plop these files in the /hyacinth/ and it should work? also is there a canada version boss

**Comment by stephanlensky** [comment]
Yup, just put the files in the root directory of the project and you should be good to go. Feel free to try adapting to Canada, but you will likely need different data files. Otherwise, Google geocoding will work worldwide.

**Comment by mattwyd** [comment]
great, i will use your blog's guide to get an api key haha then would that just go in the same file as my discord key?

**Comment by stephanlensky** [comment]
Yes, you can put it in `.env` file alongside your Discord token, or just directly modify the `settings.py` I linked

**Comment by mattwyd** [comment]
Got a key, set up billing, and I'm curious about the bot's behavior. It seems to stop after finding the first result on this page: https://www.facebook.com/marketplace/toronto/cars/, even with no filters. It marks the page for notification, and when it searches again, it stops because it already found the Camaro. How can I configure the bot to keep searching? Here's the debug info in case I'm missing something
[hya.txt](https://github.com/stephanlensky/hyacinth/files/13196729/hya.txt)
