### ISSUE TITLE
Poll Failure Log

### ISSUE THREAD

**Issue by Andreww9** [stephanlensky/hyacinth#64]
I am getting this error in my logs:

Traceback (most recent call last):
  File "/app/plugins/marketplace/client.py", line 120, in _parse_search_results
    raise ValueError("Could not find items container")
ValueError: Could not find items container

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/hyacinth/monitor.py", line 95, in __safe_poll_search
    listings = await search_spec.plugin.get_listings(search_spec.search_params, after_time)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plugins/marketplace/plugin.py", line 38, in get_listings
    return await get_listings(search_params, after_time, limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plugins/marketplace/client.py", line 28, in get_listings
    async for listing in search:
  File "/app/plugins/marketplace/client.py", line 53, in _search
    result_urls = _parse_search_results(search_content)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plugins/marketplace/client.py", line 133, in _parse_search_results
    raise ParseError("Error parsing search results", content) from e
hyacinth.exceptions.ParseError: Error parsing search results

This error was caused while parsing the following content:

<html><head></head><body></body></html>

Any help would be great, thanks!

**Comment by stephanlensky** [comment]
It looks like some of the log was cut off in your snippet - it would be helpful to see the text below "This error was caused while parsing the following content" so that we can see what the bot is seeing when it tries to load the webpage.

Would you mind sending over the complete log? Since it's probably super long, you can save it to a text file and attach it as a file instead of copying it directly into a comment.

It would also be helpful to see how you have your search configured. What is the output of `/show` in the channel that has the search?

**Comment by Andreww9** [comment]
The following is the full log, I just missed one line:

Traceback (most recent call last):
  File "/app/plugins/marketplace/client.py", line 120, in _parse_search_results
    raise ValueError("Could not find items container")
ValueError: Could not find items container

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/hyacinth/monitor.py", line 95, in __safe_poll_search
    listings = await search_spec.plugin.get_listings(search_spec.search_params, after_time)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plugins/marketplace/plugin.py", line 38, in get_listings
    return await get_listings(search_params, after_time, limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plugins/marketplace/client.py", line 28, in get_listings
    async for listing in search:
  File "/app/plugins/marketplace/client.py", line 53, in _search
    result_urls = _parse_search_results(search_content)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plugins/marketplace/client.py", line 133, in _parse_search_results
    raise ParseError("Error parsing search results", content) from e
hyacinth.exceptions.ParseError: Error parsing search results


This error was caused while parsing the following content:

<html><head></head><body></body></html>

I have attached an image of my search configuration.
![Screenshot 2023-12-20 080354](https://github.com/stephanlensky/hyacinth/assets/11082515/b026d65e-554d-45e3-95c4-08e4bab33c2b)

**Comment by stephanlensky** [comment]
Hm, that's strange - the search configuration in your screenshot is for Craigslist, but the error from your logs is for an FB Marketplace search. Were you trying out Marketplace at some point in a different channel? To help debug that I'll need the `/show` command from that channel, showing the Marketplace search that's failing.

It's also strange that there's nothing below "This error was caused while parsing the following content:" in your crash logs.

I fixed a couple of issues just now related to the Marketplace client and the crash reporting, could you try pulling the latest and seeing if it helps?

To help further, I will need that `/show` command from the channel that had the Marketplace search configured.

If you can't find it, you can try deleting all of your existing searches & filters by clearing the database with `docker-compose down -v`, then starting the bot and configuring your searches again. **Note: as mentioned, this will delete all of your existing configuration.**

**Comment by Andreww9** [comment]
You are correct, after messing with it a little further I found the FB marketplace search configuration, instead of the craigslist one.  I tried running the program today but am now getting a different error.  I posted a new issue, so until I get that resolved I will not be able to test out the changes you made.

**Comment by Andreww9** [comment]
I have resolved the other issue and testing your changes now.

**Comment by Andreww9** [comment]
Facebook marketplace notifications are now coming through, everything seems to be working!
Thanks much!
