### ISSUE TITLE
Docker Service-1 exiting 

### ISSUE THREAD

**Issue by Andreww9** [stephanlensky/hyacinth#65]
I haven't used hyacinth in roughly a week so I hopped back on today and my docker service-1 keeps exiting within seconds after starting the program.  Here is my log.

PS C:\Users\ajwwe\Documents\GitHub\hyacinth> docker-compose up service
[+] Building 0.0s (0/0)                                                                                                            docker:default 
[+] Running 3/0
 ✔ Container hyacinth-db-1           Running                                                                                                 0.0s 
 ✔ Container hyacinth-browserless-1  Created                                                                                                 0.0s 
 ✔ Container hyacinth-service-1      Created                                                                                                 0.0s 
Attaching to hyacinth-service-1
hyacinth-service-1  | 2023-12-27 17:59:28 [9] [INFO] hyacinth.discord.discord_bot We have logged in as Hyacinth#7033
hyacinth-service-1  | 2023-12-27 17:59:28 [9] [INFO] hyacinth.metrics Metrics disabled, will not start metrics write task
hyacinth-service-1  | 2023-12-27 17:59:28 [9] [INFO] hyacinth.discord.discord_bot Loading plugin plugins.craigslist.plugin:CraigslistPlugin       
hyacinth-service-1  | 2023-12-27 17:59:29 [9] [INFO] hyacinth.discord.discord_bot Loading plugin plugins.marketplace.plugin:MarketplacePlugin
hyacinth-service-1  | 2023-12-27 17:59:29 [9] [INFO] hyacinth.db.crud.notifier Found stale notifier for channel 1180163310776238154! Deleting.
hyacinth-service-1  | 2023-12-27 17:59:29 [9] [INFO] hyacinth.db.crud.notifier Found stale notifier for channel 1181439125858037850! Deleting.
hyacinth-service-1  | 2023-12-27 17:59:29 [9] [INFO] hyacinth.db.crud.notifier Found stale notifier for channel 1181435280499146792! Deleting.    
hyacinth-service-1  | 2023-12-27 17:59:29 [9] [INFO] hyacinth.db.crud.notifier Found stale notifier for channel 1186335839790321676! Deleting.    
hyacinth-service-1  | 2023-12-27 17:59:29 [9] [INFO] hyacinth.db.crud.notifier Found stale notifier for channel 1187493869177294959! Deleting.    
hyacinth-service-1  | 2023-12-27 17:59:29 [9] [INFO] hyacinth.db.crud.notifier Found stale notifier for channel 1187493831034282116! Deleting.    
hyacinth-service-1  | 2023-12-27 17:59:29 [9] [INFO] hyacinth.db.crud.notifier Found stale notifier for channel 1187493916249956392! Deleting.    
hyacinth-service-1  | 2023-12-27 17:59:29 [9] [INFO] hyacinth.db.crud.notifier Deleting 7 stale notifiers from the database.
hyacinth-service-1  | 2023-12-27 17:59:29 [9] [ERROR] hyacinth.discord.discord_bot Error in on_ready
hyacinth-service-1  | Traceback (most recent call last):
hyacinth-service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
hyacinth-service-1  |     self.dialect.do_execute(
hyacinth-service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
hyacinth-service-1  |     cursor.execute(statement, parameters)
hyacinth-service-1  | psycopg2.errors.ForeignKeyViolation: update or delete on table "channelnotifier" violates foreign key constraint "notifiersearch_notifier_id_fkey" on table "notifiersearch"
hyacinth-service-1  | DETAIL:  Key (id)=(2) is still referenced from table "notifiersearch".
hyacinth-service-1  | 
hyacinth-service-1  | 
hyacinth-service-1  | The above exception was the direct cause of the following exception:
hyacinth-service-1  | 
hyacinth-service-1  | Traceback (most recent call last):
hyacinth-service-1  |   File "/app/hyacinth/discord/discord_bot.py", line 237, in on_ready
hyacinth-service-1  |     await discord_bot.on_ready()
hyacinth-service-1  |   File "/app/hyacinth/discord/discord_bot.py", line 53, in on_ready
hyacinth-service-1  |     self.load_saved_notifiers()
hyacinth-service-1  |   File "/app/hyacinth/discord/discord_bot.py", line 63, in load_saved_notifiers
hyacinth-service-1  |     notifiers = get_channel_notifiers(session, self.client, self.monitor)
hyacinth-service-1  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hyacinth-service-1  |   File "/app/hyacinth/db/crud/notifier.py", line 116, in get_channel_notifiers
hyacinth-service-1  |     session.execute(stmt)
hyacinth-service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2308, in execute
hyacinth-service-1  |     return self._execute_internal(
hyacinth-service-1  |            ^^^^^^^^^^^^^^^^^^^^^^^
hyacinth-service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2190, in _execute_internal
hyacinth-service-1  |     result: Result[Any] = compile_state_cls.orm_execute_statement(
hyacinth-service-1  |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hyacinth-service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/bulk_persistence.py", line 1946, in orm_execute_statement
hyacinth-service-1  |     return super().orm_execute_statement(
hyacinth-service-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hyacinth-service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
hyacinth-service-1  |     result = conn.execute(
hyacinth-service-1  |              ^^^^^^^^^^^^^
hyacinth-service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
hyacinth-service-1  |     return meth(
hyacinth-service-1  |            ^^^^^
hyacinth-service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
hyacinth-service-1  |     return connection._execute_clauseelement(
hyacinth-service-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hyacinth-service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1639, in _execute_clauseelement
hyacinth-service-1  |     ret = self._execute_context(
hyacinth-service-1  |           ^^^^^^^^^^^^^^^^^^^^^^
hyacinth-service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1848, in _execute_context
hyacinth-service-1  |     return self._exec_single_context(
hyacinth-service-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
hyacinth-service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1988, in _exec_single_context
hyacinth-service-1  |     self._handle_dbapi_exception(
hyacinth-service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2343, in _handle_dbapi_exception
hyacinth-service-1  |     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
hyacinth-service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
hyacinth-service-1  |     self.dialect.do_execute(
hyacinth-service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
hyacinth-service-1  |     cursor.execute(statement, parameters)
hyacinth-service-1  | sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) update or delete on table "channelnotifier" violates foreign key constraint "notifiersearch_notifier_id_fkey" on table "notifiersearch"
hyacinth-service-1  | DETAIL:  Key (id)=(2) is still referenced from table "notifiersearch".
hyacinth-service-1  | 
hyacinth-service-1  | [SQL: DELETE FROM channelnotifier WHERE channelnotifier.channel_id IN (%(channel_id_1_1)s, %(channel_id_1_2)s, %(channel_id_1_3)s, %(channel_id_1_4)s, %(channel_id_1_5)s, %(channel_id_1_6)s, %(channel_id_1_7)s)]
hyacinth-service-1  | [parameters: {'channel_id_1_1': '1180163310776238154', 'channel_id_1_2': '1181439125858037850', 'channel_id_1_3': '1181435280499146792', 'channel_id_1_4': '1186335839790321676', 'channel_id_1_5': '1187493869177294959', 'channel_id_1_6': '1187493831034282116', 'channel_id_1_7': '1187493916249956392'}]
hyacinth-service-1  | (Background on this error at: https://sqlalche.me/e/20/gkpj)
hyacinth-service-1  | Unclosed client session
hyacinth-service-1  | client_session: <aiohttp.client.ClientSession object at 0x7f482f9a8830>
hyacinth-service-1  | Unclosed connector
hyacinth-service-1  | connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f482f81ffb0>, 23.7131339)]']
hyacinth-service-1  | connector: <aiohttp.connector.TCPConnector object at 0x7f482f927950>
hyacinth-service-1 exited with code 0

**Comment by Andreww9** [comment]
After running "docker-compose down -v" and re-running "docker-compose up service" the issue seems to be fixed.

**Comment by stephanlensky** [comment]
Glad you were able to figure it out.

I've also just fixed the bug causing this behavior, so in the future resetting the database won't be necessary.
