### ISSUE TITLE
Stuck on running the bot

### ISSUE THREAD

**Issue by tiefer** [stephanlensky/hyacinth#82]
![image](https://github.com/stephanlensky/hyacinth/assets/93172383/cb721d60-c0a3-46ca-8819-275a205ecc3d) stuck on this step i followed all instructions and went throught the path of using the local geocoder. just don't know how to actually deploy the project, please communicate any questions or context you may need/have.

**Comment by stephanlensky** [comment]
Hi @tiefer, what do you mean buy stuck deploying the bot? You need to install [Docker](https://docs.docker.com/desktop/install/windows-install/) and then run the commands shown in a command prompt.

**Comment by tiefer** [comment]
> Hi @tiefer, what do you mean buy stuck deploying the bot? You need to install [Docker](https://docs.docker.com/desktop/install/windows-install/) and then run the commands shown in a command prompt.

i have it and put in the command in command prompt and this pops up
![image](https://github.com/stephanlensky/hyacinth/assets/93172383/bb955fc0-0f7a-4c7a-9cee-72ca821ac739)

**Comment by JrVega03** [comment]
> > Hi @tiefer, what do you mean buy stuck deploying the bot? You need to install [Docker](https://docs.docker.com/desktop/install/windows-install/) and then run the commands shown in a command prompt.
> 
> i have it and put in the command in command prompt and this pops up ![image](https://private-user-images.githubusercontent.com/93172383/337096981-3828f1d8-3d15-4f99-a896-dcf2f53956f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NzAzNzgsIm5iZiI6MTcxNzY3MDA3OCwicGF0aCI6Ii85MzE3MjM4My8zMzcwOTY5ODEtMzgyOGYxZDgtM2QxNS00Zjk5LWE4OTYtZGNmMmY1Mzk1NmYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDEwMzQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiM2M2MTg3ZTIwYmM1NWM2MTdiNDY4MTJlMjE0ZWYxMmJlMzI1ODcyMjU4ODgzZmRjM2ZmMzBkNWM4Mjg3NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aWpfzoPA8IOy7aUqdRDCVzu_-4pHhzKgr3JgJ9m1UkA)

I have the same issue here

**Comment by stephanlensky** [comment]
@tiefer from your screenshot, it looks like you aren't `cd`'d into the directory where you cloned the repository. Try changing directory to inside the repository and then run the command again.

I'm going to close this issue for now, but feel free to open a new issue if you have any other problems.
